// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIpF74LxnHAAFpnCcYGr2i676zkU1dr2g',
    appId: '1:888663828264:web:ffb2c873d217b69d15d21d',
    messagingSenderId: '888663828264',
    projectId: 'cook-book-b23be',
    authDomain: 'cook-book-b23be.firebaseapp.com',
    storageBucket: 'cook-book-b23be.firebasestorage.app',
    measurementId: 'G-CDY37GWM2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrKXgiYMo2xHFcr5_pKdXyl1R6JGC0DjM',
    appId: '1:888663828264:android:35aac2b084a0e84315d21d',
    messagingSenderId: '888663828264',
    projectId: 'cook-book-b23be',
    storageBucket: 'cook-book-b23be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIW806IvBFyh5oewZ2n_NkgPAsUfj7qrA',
    appId: '1:888663828264:ios:cdd9f3e92554e55c15d21d',
    messagingSenderId: '888663828264',
    projectId: 'cook-book-b23be',
    storageBucket: 'cook-book-b23be.firebasestorage.app',
    iosBundleId: 'com.trendintools.recipeApp',
  );
}
