import 'dart:io';

/// Run after `flutter create`. Platform project scaffolding is generated by
/// your installed Flutter SDK instead of shipping unverified Gradle/Xcode files.
void replaceInFile(String path, String Function(String content) update) {
  final file = File(path);
  if (!file.existsSync()) return;
  final current = file.readAsStringSync();
  final next = update(current);
  if (next != current) file.writeAsStringSync(next);
}

void main() {
  if (!File('pubspec.yaml').existsSync()) throw StateError('Run this script from the project root.');
  replaceInFile('android/app/src/main/AndroidManifest.xml', (content) {
    var result = content.replaceAll('android:label="recipe_app"', 'android:label="Liza\'s Kitchen"');
    if (!result.contains('android.permission.INTERNET')) {
      result = result.replaceFirst(RegExp(r'<application\b'),
          '<uses-permission android:name="android.permission.INTERNET"/>\n    <application');
    }
    return result;
  });
  replaceInFile('android/app/build.gradle.kts', (content) => content.replaceAll(
      'minSdk = flutter.minSdkVersion', 'minSdk = maxOf(flutter.minSdkVersion, 24)'));
  replaceInFile('android/app/build.gradle', (content) => content.replaceAll(
      'minSdkVersion flutter.minSdkVersion', 'minSdkVersion Math.max(flutter.minSdkVersion, 24)'));
  replaceInFile('ios/Runner.xcodeproj/project.pbxproj', (content) => content.replaceAllMapped(
      RegExp(r'IPHONEOS_DEPLOYMENT_TARGET = ([0-9.]+);'), (match) {
        final major = int.tryParse(match.group(1)!.split('.').first) ?? 0;
        return major < 15 ? 'IPHONEOS_DEPLOYMENT_TARGET = 15.0;' : match.group(0)!;
      }));
  replaceInFile('ios/Podfile', (content) => content.replaceFirst(
      RegExp(r"^\s*#?\s*platform :ios, '[0-9.]+'", multiLine: true), "platform :ios, '15.0'"));
  replaceInFile('ios/Runner/Info.plist', (content) => content.replaceFirst(
      RegExp(r'(<key>CFBundleDisplayName</key>\s*<string>)[^<]*(</string>)'),
      "<key>CFBundleDisplayName</key>\n\t<string>Liza\'s Kitchen</string>"));
  replaceInFile('web/manifest.json', (content) => content.replaceAll('"recipe_app"', '"Liza\'s Kitchen"'));
  replaceInFile('web/index.html', (content) => content.replaceAll('<title>recipe_app</title>', "<title>Liza\'s Kitchen</title>"));
  final generatedTest = File('test/widget_test.dart');
  if (generatedTest.existsSync() && generatedTest.readAsStringSync().contains('Counter increments smoke test')) {
    generatedTest.deleteSync();
  }
  stdout.writeln("Configured Liza\'s Kitchen display names, Android internet permission, Android minimum, and iOS 15+.");
}
